// File generated by FlutterFire CLI / manual setup for Samagran
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZSlXpte4jBVudY502BfFItAl7AuevnvI',
    appId: '1:39473910923:android:858ba97fcef87511dc308e',
    messagingSenderId: '39473910923',
    projectId: 'samagran-80a19',
    storageBucket: 'samagran-80a19.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjv77ZKOPrN8SDCtlvfb8iT7h0i-cZIRQ',
    appId: '1:39473910923:ios:cd4b0eae37bd4871dc308e',
    messagingSenderId: '39473910923',
    projectId: 'samagran-80a19',
    storageBucket: 'samagran-80a19.firebasestorage.app',
    iosBundleId: 'com.samagran.app',
  );
}
